version: '2'
services:
    web:
        build: .
        restart: on-failure
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - db
    db:
        image: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: racine
            MONGO_INITDB_ROOT_PASSWORD: carre
            MONGO_INITDB_DATABASE: naas
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db  
        ports:
            - "27017:27017" 

volumes:
  mongodbdata:
